CREATE SEQUENCE ROTA_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE TB_ROTA (
    ID NUMBER DEFAULT ROTA_SEQ.NEXTVAL PRIMARY KEY,
    ORIGEM VARCHAR2(255) NOT NULL,
    DESTINO VARCHAR2(255) NOT NULL,
    DURACAO NUMBER NOT NULL,
    CONGESTIONADA NUMBER(1) DEFAULT 0 NOT NULL
);
